### ISSUE TITLE
If you fail installing eta sub-module, check this issue.

### ISSUE THREAD

**Issue by nsbb** [voxel51/platform-sdk#4]
When I installed platform-sdk with `sudo bash install.bash`, there was a problem.

I got a message there is no version.json file when I tried `python example/demo_image.py.`

So I checked what is the problem.

The 'eta/setup.py' or 'eta/install_externals.bash' installer didn't copy completly 'platform-sdk/eta/eta' folder at my 'local/usr/local/lib/python2.7/dist-packages/eta' folder.

After I did `sudo cp platform-sdk/eta/eta local/usr/local/lib/python2.7/dist-packages`, I could use eta as well.

Thank you. Regards.

**Comment by brimoor** [comment]
@nsbb thanks for reporting this. I fixed this error permanently by updating the `install.bash` script to install `eta` in developer mode `pip install -e .`. Now all files should be in the correct locations.
